<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>spring-boot3-brick-bootkit-parent</artifactId>
        <groupId>com.zqzqq</groupId>
        <version>4.0.5</version>
    </parent>
    <name>${project.groupId}:${project.artifactId}</name>
    <description>
        Maven packager plugin for Brick BootKit SpringBoot. It supports dev/prod/main packaging modes
        and the prepare-meta goal for standalone local development.
    </description>
    <url>https://github.com/v18268185209/brick-bootkit-springboot.git</url>
    <artifactId>spring-boot3-brick-bootkit-maven-packager</artifactId>
    <packaging>jar</packaging>

    <properties>
        <maven-plugin-api.version>3.8.4</maven-plugin-api.version>
        <maven-plugin-annotations.version>3.6.2</maven-plugin-annotations.version>
        <maven-common-artifact-filters.version>3.2.0</maven-common-artifact-filters.version>
        <commons-compress.version>1.21</commons-compress.version>
        <maven-plugin-plugin.version>3.6.0</maven-plugin-plugin.version>
    </properties>

    <dependencies>
        <!-- common -->
        <dependency>
            <groupId>com.zqzqq</groupId>
            <artifactId>spring-boot3-brick-bootkit-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- maven api -->
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>${maven-plugin-api.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <version>${maven-plugin-annotations.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.maven.shared</groupId>
            <artifactId>maven-common-artifact-filters</artifactId>
            <version>${maven-common-artifact-filters.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>${commons-compress.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-plugin-plugin</artifactId>
                <version>${maven-plugin-plugin.version}</version>
            </plugin>
        </plugins>
    </build>
</project>
